name: Trigger auto deployment for einetestapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/einetestapp-AutoDeployTrigger-65da51f4-a6ec-4927-945a-fdb17270fe47.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.EINETESTAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.EINETESTAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tuttas/tuttas/springbootwebsocketdemoapplication:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.EINETESTAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n einetestapp -g MMBBS2 --server docker.io --username  ${{ secrets.EINETESTAPP_REGISTRY_USERNAME }} --password ${{ secrets.EINETESTAPP_REGISTRY_PASSWORD }}
            az containerapp update -n einetestapp -g MMBBS2 --image tuttas/tuttas/springbootwebsocketdemoapplication:${{ github.sha }}
